### ISSUE TITLE
next steps on canopy analysis

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/climate_sensitivity_cores#56]
@ValentineHerr, thanks for running these!

Here are a few steps:
1- @ValentineHerr, something is wrong with the plots of n_cores and SSS (axis scale off on on first panel for canopy, mismatch between the set of colors in the legend and on the plot. Fixing this is an important first step.
2- @mcgregorian1, I'm pretty sure you've made a table with sample size per species/position category, but I'm not finding it right now. Can you please point us to it? 
3- @ValentineHerr, let's completely eliminate from analysis any chronology with <7 cores  
4- @ValentineHerr, please set this up so that the analysis start year has to be the same for a canopy/subcanopy pair. Then, let's record the year when both the canopy and subcanopy chronologies reach SSS>.75. We can then take a look at these to determine how far back we can go with the analysis. 
5- @mcgregorian1, you can start writing a script to do comparisons of canopy vs understory, with the recognition that this analysis is not yet final.

**Comment by mcgregorian1** [comment]
Hi @teixeirak 

2 - The table of the cores I sent to Neil is [here](https://github.com/SCBI-ForestGEO/tree-growth-and-traits/blob/master/core_list_for_neil.csv).

5 - sounds good. I can start looking at that next week (since dendrobands are today)

**Comment by ValentineHerr** [comment]
4 - Here are the starts years after removing chronologies with <7 cores and taking the maximum start year for each anopy/subcanopy pair. I guess we can keep using that 1901_2009 analysis since CAOVL goes that far back ?

Chronology|start.years.sss
--|--
CACO_subcanopy|1923
CAGL_canopy|1902
CAGL_subcanopy|1902
CAOVL_canopy|1900
CAOVL_subcanopy|1900
CATO_subcanopy|1926
FAGR_canopy|1940
FAGR_subcanopy|1940
FRAM_canopy|1929
FRAM_subcanopy|1929
FRNI_subcanopy|1940
JUNI_canopy|1930
JUNI_subcanopy|1930
LITU_canopy|1926
LITU_subcanopy|1926
PIST_canopy|1940
PIST_subcanopy|1940
QUAL_canopy|1907
QUAL_subcanopy|1907
QUPR_canopy|1910
QUPR_subcanopy|1910
QURU_canopy|1925
QURU_subcanopy|1925
QUVE_canopy|1918
QUVE_subcanopy|1918

**Comment by teixeirak** [comment]
Thanks!

Yes, let's keep using the 1901_2009 analysis, as that's the ideal for comparing canopy/subcanopy. But let's also run an analysis 1940-2009 so that we have identical comparisons across species (and can compare with traits).

**Comment by ValentineHerr** [comment]
I completed 1, 3 and 4, rerun the code and pushed everything.

**Comment by ValentineHerr** [comment]
I'll do 1940-2009.

**Comment by ValentineHerr** [comment]
I pushed 1940-2009 analysis

**Comment by teixeirak** [comment]
Thanks!
When you get a chance, could you please  run one more analysis? Let's look at just canopy chronologies (save in separate folder), dropping the requirement to start the same year as the subcanopy and going as far back both to 1901 and as far back as possible and to the year when all reach SSS=.75.

**Comment by ValentineHerr** [comment]
I added 1901-2009, 1940-2009 and 180-2009 results for canopy only [here](https://github.com/SCBI-ForestGEO/climate_sensitivity_cores/tree/master/results/canopy_only).

**Comment by teixeirak** [comment]
Thanks!
